/**
 *
 *  @Author     : HyFlo v2
 *
 *  @Name       : DerivedFlowReadingReadDTO
 *  @CreatedOn  : 03-25-2026
 *  @UpdatedOn  : 03-26-2026 — fix: add pressure, temperature, flowRate, containedVolume,
 *                              calculatedAt, calculationMethod, dataSourceId, readingSlotId,
 *                              validationStatusId, validationStatusCode to match mapper output
 *
 *  @Type       : Class
 *  @Layer      : DTO / Read
 *  @Package    : Flow / Core
 *
 **/

package dz.sh.trc.hyflo.flow.core.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonInclude;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Read DTO for DerivedFlowReading entities.
 *
 * Returned by DerivedFlowReadingMapper.toReadDTO() and
 * DerivedFlowReadingQueryService read methods.
 *
 * All fields are nullable / optional — missing values are omitted in JSON
 * output via @JsonInclude(NON_NULL).
 */
@Schema(description = "Read DTO for a derived flow reading record generated by the distribution engine")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DerivedFlowReadingReadDTO {

    @Schema(description = "Unique identifier of this derived reading")
    private Long id;

    @Schema(description = "Date this derived reading covers", example = "2026-03-20")
    private LocalDate readingDate;

    // --- Derived measurement values ---

    @Schema(description = "Derived pressure in bar", example = "67.8000")
    private BigDecimal pressure;

    @Schema(description = "Derived temperature in degrees Celsius", example = "21.5000")
    private BigDecimal temperature;

    @Schema(description = "Derived flow rate (m\u00b3/h or bpd)", example = "1100.0000")
    private BigDecimal flowRate;

    @Schema(description = "Derived contained volume in m\u00b3", example = "4500.000000")
    private BigDecimal containedVolume;

    @Schema(description = "Timestamp when this derived reading was calculated")
    private LocalDateTime calculatedAt;

    @Schema(description = "Calculation method identifier", example = "PROPORTIONAL_LENGTH")
    private String calculationMethod;

    // --- Provenance ---

    @Schema(description = "ID of the source raw FlowReading")
    private Long sourceReadingId;

    @Schema(description = "Reading date of the source raw FlowReading")
    private LocalDate sourceReadingDate;

    @Schema(description = "ID of the pipeline segment")
    private Long pipelineSegmentId;

    @Schema(description = "Code of the pipeline segment", example = "SEG-001")
    private String pipelineSegmentCode;

    @Schema(description = "ID of the validation status")
    private Long validationStatusId;

    @Schema(description = "Code of the validation status", example = "APPROVED")
    private String validationStatusCode;

    @Schema(description = "ID of the data source used for derivation")
    private Long dataSourceId;

    @Schema(description = "ID of the reading slot associated with this derived reading")
    private Long readingSlotId;
}
