/**
 *
 * 	@Author		: MEDJERAB Abir
 *
 * 	@Name		: FlowForecastDTO
 * 	@CreatedOn	: 01-23-2026
 * 	@UpdatedOn	: 01-23-2026
 *
 * 	@Type		: Class
 * 	@Layer		: DTO
 * 	@Package	: Flow / Core
 *
 **/

package dz.sh.trc.hyflo.flow.core.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonInclude;

import dz.sh.trc.hyflo.configuration.template.GenericDTO;
import dz.sh.trc.hyflo.flow.core.model.FlowForecast;
import dz.sh.trc.hyflo.flow.type.dto.ForecastTypeDTO;
import dz.sh.trc.hyflo.flow.type.model.ForecastType;
import dz.sh.trc.hyflo.general.organization.dto.EmployeeDTO;
import dz.sh.trc.hyflo.general.organization.model.Employee;
import dz.sh.trc.hyflo.network.common.dto.ProductDTO;
import dz.sh.trc.hyflo.network.common.model.Product;
import dz.sh.trc.hyflo.network.core.dto.InfrastructureDTO;
import dz.sh.trc.hyflo.network.core.model.Infrastructure;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@Data
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "Flow forecast DTO for predicted production and consumption")
public class FlowForecastDTO extends GenericDTO<FlowForecast> {

    @NotNull(message = "Forecast date is required")
    @Future(message = "Forecast date must be in the future")
    @Schema(description = "Forecast date", example = "2026-02-01", required = true)
    private LocalDate forecastDate;

    @NotNull(message = "Predicted volume is required")
    @DecimalMin(value = "0.0", inclusive = true, message = "Volume cannot be negative")
    @Digits(integer = 13, fraction = 2, message = "Volume must have at most 13 integer digits and 2 decimal places")
    @Schema(description = "Predicted volume", example = "28000.00", required = true)
    private BigDecimal predictedVolume;

    @DecimalMin(value = "0.0", message = "Confidence level cannot be negative")
    @Digits(integer = 3, fraction = 2, message = "Confidence level format: 0.00 to 100.00")
    @Min(value = 0, message = "Confidence level minimum is 0%")
    @Max(value = 100, message = "Confidence level maximum is 100%")
    @Schema(description = "Confidence level percentage", example = "85.50", minimum = "0", maximum = "100")
    private BigDecimal confidenceLevel;

    @Size(max = 100, message = "Model version must not exceed 100 characters")
    @Schema(description = "Model version used", example = "v2.3.1", maxLength = 100)
    private String modelVersion;

    @PastOrPresent(message = "Generation time cannot be in the future")
    @Schema(description = "Forecast generation timestamp", example = "2026-01-22T10:30:00")
    private LocalDateTime generatedAt;

    @Size(max = 1000, message = "Notes must not exceed 1000 characters")
    @Schema(description = "Additional notes", maxLength = 1000)
    private String notes;

    // Foreign Key IDs
    @NotNull(message = "Infrastructure is required")
    @Schema(description = "Infrastructure ID", required = true)
    private Long infrastructureId;

    @NotNull(message = "Product is required")
    @Schema(description = "Product ID", required = true)
    private Long productId;

    @NotNull(message = "Forecast type is required")
    @Schema(description = "Forecast type ID", required = true)
    private Long typeId;

    @NotNull(message = "Recording employee is required")
    @Schema(description = "Generated by employee ID", required = true)
    private Long generatedById;

    // Nested DTOs
    @Schema(description = "Infrastructure details")
    private InfrastructureDTO infrastructure;

    @Schema(description = "Product details")
    private ProductDTO product;

    @Schema(description = "Forecast type details")
    private ForecastTypeDTO type;

    @Schema(description = "Generated by employee details")
    private EmployeeDTO generatedBy;

    @Override
    public FlowForecast toEntity() {
        FlowForecast entity = new FlowForecast();
        entity.setId(getId());
        entity.setForecastDate(this.forecastDate);
        entity.setPredictedVolume(this.predictedVolume);
        entity.setConfidenceLevel(this.confidenceLevel);
        entity.setModelVersion(this.modelVersion);
        entity.setGeneratedAt(this.generatedAt);
        entity.setNotes(this.notes);

        if (this.infrastructureId != null) {
            Infrastructure infrastructure = new Infrastructure();
            infrastructure.setId(this.infrastructureId);
            entity.setInfrastructure(infrastructure);
        }

        if (this.productId != null) {
            Product product = new Product();
            product.setId(this.productId);
            entity.setProduct(product);
        }

        if (this.typeId != null) {
            ForecastType type = new ForecastType();
            type.setId(this.typeId);
            entity.setType(type);
        }

        if (this.generatedById != null) {
            Employee employee = new Employee();
            employee.setId(this.generatedById);
            entity.setGeneratedBy(employee);
        }

        return entity;
    }

    @Override
    public void updateEntity(FlowForecast entity) {
        if (this.forecastDate != null) entity.setForecastDate(this.forecastDate);
        if (this.predictedVolume != null) entity.setPredictedVolume(this.predictedVolume);
        if (this.confidenceLevel != null) entity.setConfidenceLevel(this.confidenceLevel);
        if (this.modelVersion != null) entity.setModelVersion(this.modelVersion);
        if (this.generatedAt != null) entity.setGeneratedAt(this.generatedAt);
        if (this.notes != null) entity.setNotes(this.notes);

        if (this.infrastructureId != null) {
            Infrastructure infrastructure = new Infrastructure();
            infrastructure.setId(this.infrastructureId);
            entity.setInfrastructure(infrastructure);
        }

        if (this.productId != null) {
            Product product = new Product();
            product.setId(this.productId);
            entity.setProduct(product);
        }

        if (this.typeId != null) {
            ForecastType type = new ForecastType();
            type.setId(this.typeId);
            entity.setType(type);
        }

        if (this.generatedById != null) {
            Employee employee = new Employee();
            employee.setId(this.generatedById);
            entity.setGeneratedBy(employee);
        }
    }

    public static FlowForecastDTO fromEntity(FlowForecast entity) {
        if (entity == null) return null;

        return FlowForecastDTO.builder()
                .id(entity.getId())
                .forecastDate(entity.getForecastDate())
                .predictedVolume(entity.getPredictedVolume())
                .confidenceLevel(entity.getConfidenceLevel())
                .modelVersion(entity.getModelVersion())
                .generatedAt(entity.getGeneratedAt())
                .notes(entity.getNotes())

                .infrastructureId(entity.getInfrastructure() != null ? entity.getInfrastructure().getId() : null)
                .productId(entity.getProduct() != null ? entity.getProduct().getId() : null)
                .typeId(entity.getType() != null ? entity.getType().getId() : null)
                .generatedById(entity.getGeneratedBy() != null ? entity.getGeneratedBy().getId() : null)

                .infrastructure(entity.getInfrastructure() != null ? InfrastructureDTO.fromEntity(entity.getInfrastructure()) : null)
                .product(entity.getProduct() != null ? ProductDTO.fromEntity(entity.getProduct()) : null)
                .type(entity.getType() != null ? ForecastTypeDTO.fromEntity(entity.getType()) : null)
                .generatedBy(entity.getGeneratedBy() != null ? EmployeeDTO.fromEntity(entity.getGeneratedBy()) : null)
                .build();
    }
}
