package dz.sh.trc.hyflo.core.network.topology.dto.response;

import java.time.LocalDate;
import java.util.Set;

public record PipelineSegmentResponse(
        Long id,
        String code,
        String name,
        LocalDate installationDate,
        LocalDate commissioningDate,
        LocalDate decommissioningDate,
        Long operationalStatusId,
        String operationalStatusDesignationFr,
        Long ownerId,
        String ownerDesignationFr,
        Double diameter,
        Double length,
        Double thickness,
        Double roughness,
        Double startPoint,
        Double endPoint,
        Long constructionMaterialId,
        String constructionMaterialDesignationFr,
        Long exteriorCoatingId,
        String exteriorCoatingDesignationFr,
        Long interiorCoatingId,
        String interiorCoatingDesignationFr,
        Long pipelineId,
        String pipelineDesignationFr,
        Long departureFacilityId,
        String departureFacilityDesignationFr,
        Long arrivalFacilityId,
        String arrivalFacilityDesignationFr,
        String terrainType,
        String environmentSensitivity,
        Double corrosionIndex,
        String criticality
) {}