package dz.sh.trc.hyflo.intelligence.assistant.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.util.List;

/**
 * Request DTO for a single operator message sent to the HyFlo assistant.
 *
 * <p>Passed from {@link dz.sh.trc.hyflo.intelligence.assistant.controller.AssistantController}
 * into {@link dz.sh.trc.hyflo.intelligence.assistant.service.OperatorAssistantService}
 * and forwarded to the platform layer via
 * {@link dz.sh.trc.hyflo.intelligence.assistant.port.AssistantAgentPort}.</p>
 *
 * <p>The {@code sessionId} groups turns of a conversation so the platform
 * adapter can maintain short-term memory within a session window.</p>
 */
public record AssistantRequestDTO(

        /**
         * The operator's free-text message or question.
         */
        @NotBlank(message = "Prompt must not be blank")
        @Size(max = 4000, message = "Prompt must not exceed 4000 characters")
        String prompt,

        /**
         * Conversation session identifier.
         * Generated by the client on first turn and reused for follow-ups.
         * Null on first message — the service will assign a new session ID.
         */
        String sessionId,

        /**
         * Optional domain context injected into the LLM prompt.
         * Examples: active pipeline ID, current alert ID, segment ref.
         * Kept to a maximum of 10 entries to control prompt size.
         */
        @Size(max = 10, message = "Context entries must not exceed 10")
        List<AssistantContextEntryDTO> context,

        /**
         * Correlation ID propagated from the HTTP request header (X-Correlation-ID).
         */
        String correlationId
) {
        /**
         * A single domain context entry injected into the assistant prompt.
         */
        public record AssistantContextEntryDTO(

                @NotBlank(message = "Context key must not be blank")
                String key,

                @NotBlank(message = "Context value must not be blank")
                String value
        ) {}
}