/**
 *
 * 	@Author		: HyFlo v2
 *
 * 	@Name		: DerivedFlowReading
 * 	@CreatedOn	: 03-25-2026
 * 	@UpdatedOn	: 03-25-2026
 * 	@UpdatedOn	: 03-26-2026 — fix: add pressure, temperature, flowRate, containedVolume,
 *                              calculatedAt, calculationMethod, validationStatus FK,
 *                              dataSourceId, readingSlotId — required by mapper and
 *                              SegmentDistributionServiceImpl
 *
 * 	@Type		: Class
 * 	@Layer		: Model
 * 	@Package	: Flow / Core
 *
 **/

package dz.sh.trc.hyflo.flow.core.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import dz.sh.trc.hyflo.configuration.template.GenericModel;
import dz.sh.trc.hyflo.flow.common.model.ReadingSlot;
import dz.sh.trc.hyflo.flow.common.model.ValidationStatus;
import dz.sh.trc.hyflo.network.core.model.PipelineSegment;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents a derived (computed) flow reading on a pipeline segment,
 * generated by SegmentDistributionService after a source FlowReading is APPROVED.
 *
 * <h3>Generation strategy</h3>
 * Each approved FlowReading produces one DerivedFlowReading per active
 * PipelineSegment, using proportional-length distribution of the source
 * volume across segments.
 *
 * <h3>Time-slot integrity</h3>
 * Each derived reading is optionally scoped to a {@link ReadingSlot}.
 * The composite unique constraint {@code T_04_01_02_UK_01 (readingDate,
 * pipelineSegment, sourceReading)} prevents duplicate derived records
 * for the same segment and source reading.
 *
 * <h3>Analytics index</h3>
 * {@code T_04_01_02_IX_01} on readingDate + pipelineSegment supports
 * the primary time-range analytical query pattern.
 */
@Schema(description = "Computed flow reading derived from an approved raw FlowReading, distributed per pipeline segment")
@Setter
@Getter
@ToString
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor
@Entity(name = "DerivedFlowReading")
@Table(
        name = "T_03_03_03",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "T_03_03_03_UK_01",
                        columnNames = {"F_01", "F_06", "F_07"}
                )
        },
        indexes = {
                @Index(
                        name = "T_03_03_03_IX_01",
                        columnList = "F_01, F_06"
                )
        }
)
public class DerivedFlowReading extends GenericModel {

    // ------------------------------------------------------------------
    // F_01 — Date dimension
    // ------------------------------------------------------------------

    @Schema(description = "Date the derived reading covers", example = "2026-03-20")
    @Column(name = "F_01", nullable = false)
    private LocalDate readingDate;

    // ------------------------------------------------------------------
    // F_02..F_07 — Derived measurement fields
    // ------------------------------------------------------------------

    @Schema(description = "Derived pressure in bar for this segment", example = "67.8")
    @Column(name = "F_02", precision = 10, scale = 4)
    private BigDecimal pressure;

    @Schema(description = "Derived temperature in degrees Celsius for this segment", example = "21.5")
    @Column(name = "F_03", precision = 10, scale = 4)
    private BigDecimal temperature;

    @Schema(description = "Derived flow rate (m\u00b3/h or bpd) for this segment", example = "1100.0000")
    @Column(name = "F_04", precision = 18, scale = 4)
    private BigDecimal flowRate;

    @Schema(description = "Derived contained volume in m\u00b3 proportional to segment length", example = "4500.0000")
    @Column(name = "F_05", precision = 18, scale = 6)
    private BigDecimal containedVolume;

    @Schema(description = "Timestamp when this derived reading was calculated")
    @Column(name = "F_06")
    private LocalDateTime calculatedAt;

    @Schema(description = "Calculation method or model identifier", example = "PROPORTIONAL_LENGTH")
    @Column(name = "F_07", length = 100)
    private String calculationMethod;

    // ------------------------------------------------------------------
    // F_08 — Denormalised scalar IDs (optional provenance)
    // ------------------------------------------------------------------

    @Schema(description = "ID of the data source used for this derivation (denormalised scalar for performance)")
    @Column(name = "F_08")
    private Long dataSourceId;

    @Schema(description = "ID of the reading slot associated with this derived reading (denormalised scalar)")
    @Column(name = "F_09")
    private Long readingSlotId;

    // ------------------------------------------------------------------
    // FK — PipelineSegment (core network entity, part of unique key)
    // ------------------------------------------------------------------

    @Schema(description = "FK to pipeline segment (canonical network/core ownership)")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "F_10", referencedColumnName = "F_00",
            foreignKey = @ForeignKey(name = "T_03_03_03_FK_01"), nullable = false)
    private PipelineSegment pipelineSegment;

    // ------------------------------------------------------------------
    // FK — Source raw reading (part of unique key)
    // ------------------------------------------------------------------

    @Schema(description = "FK to the source raw FlowReading from which this reading was derived")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "F_11", referencedColumnName = "F_00",
            foreignKey = @ForeignKey(name = "T_03_03_03_FK_02"))
    private FlowReading sourceReading;

    // ------------------------------------------------------------------
    // FK — ReadingSlot (optional; time-window provenance)
    // ------------------------------------------------------------------

    @Schema(description = "FK to the time slot this derived reading optionally covers")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "F_12", referencedColumnName = "F_00",
            foreignKey = @ForeignKey(name = "T_03_03_03_FK_03"))
    private ReadingSlot readingSlot;

    // ------------------------------------------------------------------
    // FK — ValidationStatus (optional; inherited from source reading)
    // ------------------------------------------------------------------

    @Schema(description = "Validation status inherited from source reading (optional projection)")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "F_13", referencedColumnName = "F_00",
            foreignKey = @ForeignKey(name = "T_03_03_03_FK_04"))
    private ValidationStatus validationStatus;
}
