package dz.sh.trc.hyflo.intelligence.crisis.dto;

import java.time.Instant;
import java.util.List;

/**
 * Structured operational recommendations generated by the AI
 * for responding to an active crisis event.
 */
public record CrisisRecommendationDTO(

        String crisisEventId,
        String pipelineId,

        /**
         * Prioritised list of recommended actions for field teams.
         */
        List<ActionItemDTO> actionItems,

        /**
         * Estimated time to containment in minutes, as assessed by AI.
         * Null if the AI cannot estimate.
         */
        Integer estimatedContainmentMinutes,

        /**
         * AI-generated escalation guidance (e.g. notify authority, shutdown valve).
         */
        String escalationGuidance,

        String aiProvider,
        Instant generatedAt,
        String correlationId
) {
    /**
     * A single prioritised action step.
     */
    public record ActionItemDTO(

            /**
             * Execution priority: 1 = highest.
             */
            int priority,

            /**
             * Action category: ISOLATE | EVACUATE | NOTIFY | INSPECT
             * | SHUTDOWN | MONITOR | REPAIR
             */
            String category,

            String description,
            String responsibleRole,

            /**
             * Recommended completion deadline in minutes from now.
             */
            int deadlineMinutes
    ) {}
}